// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: entry.sql

package db

import (
	"context"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
    "account_number",
    "amount"
) VALUES (
             $1, $2
         ) RETURNING id, account_number, amount, created_at, updated_at
`

type CreateEntryParams struct {
	AccountNumber int64 `json:"account_number"`
	Amount        int64 `json:"amount"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry, arg.AccountNumber, arg.Amount)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountNumber,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT id, account_number, amount, created_at, updated_at FROM entries
WHERE account_number = $1 LIMIT 1
`

func (q *Queries) GetEntry(ctx context.Context, accountNumber int64) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, accountNumber)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountNumber,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT id, account_number, amount, created_at, updated_at FROM entries
WHERE account_number = $1
ORDER BY id
    LIMIT $2
OFFSET $3
`

type ListEntriesParams struct {
	AccountNumber int64 `json:"account_number"`
	Limit         int32 `json:"limit"`
	Offset        int32 `json:"offset"`
}

func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntries, arg.AccountNumber, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entry{}
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.AccountNumber,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
