// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"time"
)

type Account struct {
	ID            int64     `json:"id"`
	AccountNumber int64     `json:"account_number"`
	Owner         string    `json:"owner"`
	Balance       int64     `json:"balance"`
	Currency      string    `json:"currency"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type Entry struct {
	ID            int64 `json:"id"`
	AccountNumber int64 `json:"account_number"`
	// can be negative or positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Transfer struct {
	ID                int64     `json:"id"`
	FromAccountNumber int64     `json:"from_account_number"`
	ToAccountNumber   int64     `json:"to_account_number"`
	Amount            int64     `json:"amount"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}
